# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.TimeField(default=datetime.datetime(2016, 11, 5, 23, 7, 43, 324000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
